### ISSUE TITLE
Compatibility with Django 1.10: Attribute error

### ISSUE THREAD

**Issue by PetrDlouhy** [django-polymorphic/django-polymorphic#225]
When running django-polymorphic on upcoming Django 1.10, following error is raised:
```
Traceback (most recent call last):
  File "runtests.py", line 83, in <module>
    runtests()
  File "runtests.py", line 80, in runtests
    execute_from_command_line(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/apps/config.py", line 206, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/build/PetrDlouhy/django-polymorphic/polymorphic/models.py", line 31, in <module>
    class PolymorphicModel(six.with_metaclass(PolymorphicModelBase, models.Model)):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/home/travis/build/PetrDlouhy/django-polymorphic/polymorphic/base.py", line 90, in __new__
    new_class._default_manager = user_manager._copy_to_model(new_class)
AttributeError: 'PolymorphicManager' object has no attribute '_copy_to_model'
```

**Comment by JasonYao** [comment]
Commenting here as well to say this issue is still persisting as of Aug 2nd.

uWSGI log:
> *** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./Test/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/server/.env/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/server/.env/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/server/.env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/server/.env/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/server/.env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/server/.env/lib/python3.5/site-packages/polymorphic/models.py", line 30, in <module>
    class PolymorphicModel(six.with_metaclass(PolymorphicModelBase, models.Model)):
  File "/server/.env/lib/python3.5/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/server/.env/lib/python3.5/site-packages/polymorphic/base.py", line 90, in __new__
    new_class._default_manager = user_manager._copy_to_model(new_class)
AttributeError: 'PolymorphicManager' object has no attribute '_copy_to_model'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 15917)
Tue Aug  2 09:37:04 2016 - [emperor] vassal Test.ini has been spawned
spawned uWSGI worker 1 (pid: 15919, cores: 1)
spawned uWSGI worker 2 (pid: 15920, cores: 1)
spawned uWSGI worker 3 (pid: 15921, cores: 1)
Tue Aug  2 09:37:04 2016 - [emperor] vassal Test.ini is ready to accept requests
spawned uWSGI worker 4 (pid: 15922, cores: 1)
spawned uWSGI worker 5 (pid: 15923, cores: 1)
--- no python application found, check your startup logs for errors ---

**Comment by jjkester** [comment]
Found the commit that removed this from the class(es) inherited by polymorphic: https://github.com/django/django/commit/3a47d42fa33012b2156bf04058d933df6b3082d2

**Comment by bartoszhernas** [comment]
Hi, is someone already working on fix for this? Sadly, it also breaks `dj-stripe` :(

**Comment by vdboor** [comment]
I've started a django110 branch.

The main issue is the new way the default manager is assigned. Other packages (e.g. django-mptt) are also struggling with this.

**Comment by sivabudh** [comment]
+1. Running into this problem as well on Django 1.10.

**Comment by jjkester** [comment]
Does anyone know a place where this new way of assigning a manager is documented? I am happy to help, but I am not entirely sure I want to dig through the source code to find this out.

**Comment by vdboor** [comment]
@jjkester I just found out that removing all metaclass-magic that polymorphic added with managers works really nicely.

The master branch is now Django 1.10. I'd love to hear your feedback before I release that as 1.0

**Comment by jjkester** [comment]
Commit ref: https://github.com/django-polymorphic/django-polymorphic/commit/cf1d4b532d34b013478061f83df1bf2ca4eb3701

**Comment by jjkester** [comment]
@vdboor I never understood all the magic (probably required for older Django versions?). From the commit I understand that Django 1.10 makes stuff easier, which is nice :smile: . Can you explain in words what the metaclass stuff actually does/did?

**Comment by vdboor** [comment]
It make sure that all derived classes had a polymorphic manager - this made sure there is polymorphic behavior for all models. In earlier Django versions, the polymorphic manager was not inherited (because `PolymorphicModel` is an abstract class). That code is one of the oldest and "Here be dragons" parts of polymorphic which I tried cleaning up when I took over maintenance - but also carefully kept identical to how it worked.

**Comment by jjkester** [comment]
Right. Thanks for the explanation. I will take a good look at it, if I have any comments I will place them here. (If I don't, I will complement you here of course.)

**Comment by jjkester** [comment]
Well, your code for avoiding the magic looks fine and logical, so it seems okay. I have not tested the code with a real-life project because it would take a bit too much time - I do trust the unit tests I guess (assuming they don't fail).

I see the tests on Python 3 are fixed now as well :smiley: 

I don't think I know the model layer good enough to suggest any other approaches to this, so I guess "good job" is fair to say :wink:

**Comment by vdboor** [comment]
**I've just released a 1.0b1 version to PyPI for testing**

Please let me know how it works for you!

**Comment by Diaoul** [comment]
Works for me :+1:

**Comment by blag** [comment]
Works for me too. 👍 😄

**Comment by jjkester** [comment]
I have tested a real-world project with the released beta version on PyPI, works perfectly.

**Comment by ellmetha** [comment]
Works perfectly for me too. :wink:

**Comment by vdboor** [comment]
Great to hear! I'm waiting for the latest tests on the `StackedPolymorphicInline` (also part of 1.0) before the final version is released.

**Comment by wiesson** [comment]
Works for me too. Any release date in sight?

**Comment by Kianoosh76** [comment]
Hi all!
There seems to be a similar bug for me
Does anyone have idea about it?
`Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "//anaconda/envs/test/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "//anaconda/envs/test/lib/python3.5/site-packages/polymorphic_tree/models.py", line 71, in <module>
    class PolymorphicMPTTModel(with_metaclass(PolymorphicMPTTModelBase, MPTTModel, PolymorphicModel)):
  File "//anaconda/envs/test/lib/python3.5/site-packages/future/utils/__init__.py", line 137, in __new__
    return meta(name, bases, d)
  File "//anaconda/envs/test/lib/python3.5/site-packages/mptt/models.py", line 263, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "//anaconda/envs/test/lib/python3.5/site-packages/polymorphic/base.py", line 68, in __new__
    new_class = self.call_superclass_new_method(model_name, bases, attrs)
  File "//anaconda/envs/test/lib/python3.5/site-packages/polymorphic/base.py", line 202, in call_superclass_new_method
    new_class = super(PolymorphicModelBase, self).__new__(self, model_name, bases, attrs)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/db/models/base.py", line 157, in __new__
    new_class.add_to_class(obj_name, obj)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "//anaconda/envs/test/lib/python3.5/site-packages/mptt/managers.py", line 82, in contribute_to_class
    super(TreeManager, self).contribute_to_class(model, name)
  File "//anaconda/envs/test/lib/python3.5/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
AttributeError: can't set attribute
`

**Comment by vdboor** [comment]
The v1.0.1 release is out, that works on Django 1.10.1 as well!
