### ISSUE TITLE
Only base classes provided in Django 1.11b1

### ISSUE THREAD

**Issue by adamcharnock** [django-polymorphic/django-polymorphic#267]
I'm testing a project against Django 1.11b1 and it seems that only the base model is being returned in the resulting ``PolymorphicQuerySet``. Only upon calling ``get_real_instances()`` to I get the actual model instances.

Here is my working:

```python
>>> Action.objects.all()
# 'Action' is the base class
<PolymorphicQuerySet [<Action: Action object>, <Action: Action object>, <Action: Action object>, <Action: Action object>]>
>>> Action.objects.all().get_real_instances()
# Now the resolution works
[<EmailAction: Email toby@example.com>, <EmailAction: Email adam@example.com>, <EmailAction: Email foo@example.com>, <EmailAction: Email bar@example.com>]
```

This seemed to work when testing against Django 1.10.

**Comment by jleclanche** [comment]
So, the tests don't get far on Django 1.11:

```
Traceback (most recent call last):
  File "runtests.py", line 94, in <module>
    runtests()
  File "runtests.py", line 91, in runtests
    execute_from_command_line(argv)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/test/runner.py", line 602, in run_tests
    self.run_checks()
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/test/runner.py", line 562, in run_checks
    call_command('check', verbosity=self.verbosity)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/home/adys/tmp/django-polymorphic/.tox/django111/lib/python3.6/site-packages/django/core/management/base.py", line 405, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
                                                                                                                                                                                                                                       
ERRORS:
polymorphic.MRODerived: (models.E005) The field 'id' from parent model 'polymorphic.mrobase3' clashes with the field 'id' from parent model 'polymorphic.mrobase1'.

System check identified 1 issue (0 silenced).
```

**Comment by meshy** [comment]
I've been attemping to address this issue in https://github.com/django-polymorphic/django-polymorphic/pull/271.

I fixed that particular traceback in https://github.com/django-polymorphic/django-polymorphic/pull/271/commits/8e52bdf6d146a3df533177bd47eaf05076466644

**Comment by vdboor** [comment]
We have tests running now in Django 1.11 thanks to @meshy!

Sadly, they clearly show what you report here.
If anyone could look into Django 1.11 compatibility, that would really help speeding up a new release!
