### ISSUE TITLE
AttributeError: type object 'FeedbackBase' has no attribute 'polymorphic_primary_key_name'

### ISSUE THREAD

**Issue by vosi** [django-polymorphic/django-polymorphic#302]
```
The following content types are stale and need to be deleted:

    app | deleted_model1
    app | deleted_model2

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/contenttypes/management.py", line 166, in update_contenttypes
    ct.delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 957, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 226, in collect
    elif sub_objs:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 264, in __nonzero__
    return type(self).__bool__(self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 260, in __bool__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/polymorphic/query.py", line 53, in _polymorhic_iterator
    real_results = queryset._get_real_instances(base_result_objects)
  File "/usr/local/lib/python2.7/dist-packages/polymorphic/query.py", line 362, in _get_real_instances
    pk_name = self.model.polymorphic_primary_key_name
AttributeError: type object 'FeedbackBase' has no attribute 'polymorphic_primary_key_name'
```

app.deleted_model1, app.deleted_model2 has nothing to do with PolymorphicModel

**Comment by vdboor** [comment]
It seems that the deleted models have references to a polymorphic model. I'll need to see your model definition to make sense of the error message.
