### ISSUE TITLE
Syntax error testing admin

### ISSUE THREAD

**Issue by tony** [django-polymorphic/django-polymorphic#329]
master 02b71d8

```
Traceback (most recent call last):
  File "runtests.py", line 81, in <module>
    runtests()
  File "runtests.py", line 77, in runtests
    execute_from_command_line(argv)
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/me/work/python/django-polymorphic/.tox/py36-django111/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/me/work/python/django-polymorphic/polymorphic/admin/__init__.py", line 9, in <module>
    from .childadmin import PolymorphicChildModelAdmin                                                                                                                                                               File "/Users/me/work/python/django-polymorphic/polymorphic/admin/childadmin.py", line 186
    if self.fieldsets or or self.fields or not self.base_fieldsets:
```

**Comment by vdboor** [comment]
Fixed!
