### ISSUE TITLE
Tests Fail when run in the normal test

### ISSUE THREAD

**Issue by glassresistor** [django-polymorphic/django-polymorphic#42]
When running tests on polymorphic when in my own project I'm getting these failed tests.  I'm using postgres 9.2 and django 1.5.1 w/ py2.7 in 12.

```
 ./manage.py test polymorphic
Creating test database for alias 'default'...
.....
# known django model inheritance diamond problem detected
DiamondXY fields 1: field_b "", field_x "x", field_y "y"
DiamondXY fields 2: field_b "", field_x "x", field_y "y"
.E.FFF..F..FFF
# known type inconstency with custom primary key field detected (django problem?)
....FFFF.
======================================================================
ERROR: test_extra_method (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 523, in test_extra_method
    self.assertEqual(repr(objects[0]), '<Model2B: id 2, field1 (CharField), field2 (CharField)>')
IndexError: list index out of range

======================================================================
FAIL: test_foreignkey_field (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 471, in test_foreignkey_field
    self.assertEqual(repr(object2a.model2b), '<Model2B: id 3, field1 (CharField), field2 (CharField)>')
AssertionError: '<Model2B: id 11, field1 (CharField), field2 (CharField)>' != '<Model2B: id 3, field1 (CharField), field2 (CharField)>'

======================================================================
FAIL: test_get_real_instances (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 426, in test_get_real_instances
    self.assertEqual(repr(objects[0]), '<Model2A: id 1, field1 (CharField)>')
AssertionError: '<Model2A: id 13, field1 (CharField)>' != '<Model2A: id 1, field1 (CharField)>'

======================================================================
FAIL: test_instance_of_filter (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 553, in test_instance_of_filter
    self.assertEqual(repr(objects[0]), '<Model2B: id 2, field1 (CharField), field2 (CharField)>')
AssertionError: '<Model2B: id 18, field1 (CharField), field2 (CharField)>' != '<Model2B: id 2, field1 (CharField), field2 (CharField)>'

======================================================================
FAIL: test_manual_get_real_instance (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 407, in test_manual_get_real_instance
    self.assertEqual(repr(o.get_real_instance()), '<Model2C: id 3, field1 (CharField), field2 (CharField), field3 (CharField)>')
AssertionError: '<Model2C: id 23, field1 (CharField), field2 (CharField), field3 (CharField)>' != '<Model2C: id 3, field1 (CharField), field2 (CharField), field3 (CharField)>'

======================================================================
FAIL: test_non_polymorphic (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 414, in test_non_polymorphic
    self.assertEqual(repr(objects[0]), '<Model2A: id 1, field1 (CharField)>')
AssertionError: '<Model2A: id 25, field1 (CharField)>' != '<Model2A: id 1, field1 (CharField)>'

======================================================================
FAIL: test_onetoone_field (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 484, in test_onetoone_field
    self.assertEqual(repr(b.one2one), '<Model2A: id 3, field1 (CharField)>')
AssertionError: '<Model2A: id 31, field1 (CharField)>' != '<Model2A: id 3, field1 (CharField)>'

======================================================================
FAIL: test_polymorphic___filter (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 580, in test_polymorphic___filter
    self.assertEqual(repr(objects[0]), '<Model2B: id 2, field1 (CharField), field2 (CharField)>')
AssertionError: '<Model2B: id 34, field1 (CharField), field2 (CharField)>' != '<Model2B: id 2, field1 (CharField), field2 (CharField)>'

======================================================================
FAIL: test_relation_base (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 641, in test_relation_base
    self.assertEqual(repr(objects[0]), '<RelationB: id 3, field_base (CharField) "B1", fk (ForeignKey) RelationA, field_b (CharField) "B2", m2m (ManyToManyField) 1>')
AssertionError: '<RelationBC: id 4, field_base (CharField) "C1", fk (ForeignKey) RelationA, field_b (CharField) "C2", field_c (CharField) "C3", m2m (ManyToManyField) 0>' != '<RelationB: id 3, field_base (CharField) "B1", fk (ForeignKey) RelationA, field_b (CharField) "B2", m2m (ManyToManyField) 1>'

======================================================================
FAIL: test_simple_inheritance (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 397, in test_simple_inheritance
    self.assertEqual(repr(objects[0]), '<Model2A: id 1, field1 (CharField)>')
AssertionError: '<Model2A: id 37, field1 (CharField)>' != '<Model2A: id 1, field1 (CharField)>'

======================================================================
FAIL: test_translate_polymorphic_q_object (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 444, in test_translate_polymorphic_q_object
    self.assertEqual(repr(objects[0]), '<Model2C: id 3, field1 (CharField), field2 (CharField), field3 (CharField)>')
AssertionError: '<Model2C: id 43, field1 (CharField), field2 (CharField), field3 (CharField)>' != '<Model2C: id 3, field1 (CharField), field2 (CharField), field3 (CharField)>'

======================================================================
FAIL: test_user_defined_manager (polymorphic.tests.PolymorphicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mike/code/django_polymorphic/polymorphic/tests.py", line 661, in test_user_defined_manager
    self.assertEqual(repr(objects[0]), '<ModelWithMyManager: id 6, field1 (CharField) "D1b", field4 (CharField) "D4b">')
AssertionError: '<ModelWithMyManager: id 50, field1 (CharField) "D1b", field4 (CharField) "D4b">' != '<ModelWithMyManager: id 6, field1 (CharField) "D1b", field4 (CharField) "D4b">'

----------------------------------------------------------------------
Ran 28 tests in 0.554s

FAILED (failures=11, errors=1)
Destroying test database for alias 'default'...
```

**Comment by hobarrera** [comment]
This has been fixed by #312  and #303. The latter actually introduces postgres to CI.

It should be safe to close this.
